### PR TITLE
Update to Python 3 and added new required fields to message

### PR DESCRIPTION
**Pull request by joshuafuller**
See: https://github.com/sofwerx/push-cursor-on-target/pull/4

### CODE REVIEW

**Comment by Tissy** [comment]
Hi Josh, how would I add the "Remarks" field to this please?

many thanks

**Comment by joshuafuller** [comment]
This document has some references on how to add the REMARKS field. Although I haven't used it, it looks like a standard field.

http://www.dodccrp.org/events/2006_CCRTS/html/papers/073.pdf

**Comment by joshuafuller** [comment]
Hi Tissy,

Building upon my previous response where I mentioned that the REMARKS field is a standard field, let me guide you on how to implement this in the codebase.

**File to Modify**: `CoT.py`

**Function to Modify**: `atoms` within the `CursorOnTarget` class.

**Steps**:
1. Add an additional parameter called `remarks` to the `atoms` method. Set its default value to `None`.
2. Inside the `atoms` method, after creating the `<detail>` element, add a new sub-element called `<remarks>` and set its text content to the value passed in the `remarks` parameter.

Here’s the code snippet:

```
class CursorOnTarget:
    # ... other parts of the code ...
    
    def atoms(__self, unit, remarks=None):
        # ... existing code ...
        
        # Create the 'detail' element
        detail = ET.SubElement(cot, 'detail')
        
        # Add the 'remarks' element to 'detail' if remarks are provided
        if remarks is not None:
            ET.SubElement(detail, 'remarks').text = remarks
        
        # ... existing code ...

```
Usage Example:
When calling the atoms method, you can now pass in the remarks as an additional argument, like this:

`cot_message = cursor_on_target.atoms(unit, remarks="This is a remark")`

This modification aligns with the standard structure of CoT messages as outlined in the document I referenced earlier.

Let me know if you need further clarification!

Best regards,
Josh

**Comment by Tissy** [comment]
Hi Josh,

Thank you very much for taking the time to reply, much appreciated.

Tried the implementation, unfortunately I can't get it to work.

In the  `testCoT.py`, I have the following:

```
params = {  # SWX parking lot
    "lat": 27.957261,
    "lon": -82.436587,
    "uid": "Nerd Herd",
    "identity": "hostile",
    "dimension": "land-unit",
    "entity": "military",
    "type": "U-C",
    "remarks": "This is a test remark"
}
```
Then in the `CoT.py`, I have the following:

```
class CursorOnTarget:

    @staticmethod
    def atoms(__self, unit, remarks=None):
        # ... existing code ...

        # Event fields
        event_attr = {
            "version": "2.0",
            "uid": cot_id,
            "how": "m-g",
            "time": zulu,
            "start": zulu,
            "stale": stale,
            "type": cot_type
        }

        # Point fields
        point_attr = {
            "lat": str(unit["lat"]),
            "lon": str(unit["lon"]),
            "hae": str(unit["hae"]),
            "ce": "9999999.0",    #unit["ce"],
            "le": "9999999.0"     #unit["le"]
        }

        cot = ET.Element('event', attrib=event_attr)
        ET.SubElement(cot, 'detail')
        ET.SubElement(cot, 'point', attrib=point_attr)

        # Add the 'remarks' element to 'detail' if remarks are provided
        if remarks is not None:
            ET.SubElement(detail, 'remarks').text = remarks
    
        # ... existing code ...
```
I believe the schema should look like this, but the remarks aren't populating?

`<detail><remarks>This is a test remark</remarks><contact callsign='12345' /></detail></event>`

Any further suggestions please?

Many thanks again,

Steve

**Comment by joshuafuller** [comment]
I have to admit, my last reply was off the cuff without trying any code. I’ll work on some code first chance I get to test it out and see if it will work in ATAK. Might not be today though.

**Comment by Tissy** [comment]
Thank you Josh.  After some perseverance, I think I may have solved it.  I also added a couple more elements.

Essentially, in the `testCoT.py` file I added the following:

```
params = {  # SWX parking lot
    "lat": 27.957261,
    "lon": -82.436587,
    "uid": "Nerd Herd",
    "identity": "hostile",
    "dimension": "land-unit",
    "entity": "military",
    "type": "U-C"
    "remarks": "Test Message",
    "callsign": "12345",
    "course": "0",
    "speed": "0"
#    "type": "U-C-R-H"
}}
```

Then, I added the following to the `CoT.py` file.

```
class CursorOnTarget:

    @staticmethod
    def atoms(unit):

        # ... existing code ...

        # Detail fields
        detail_attr = {
            "callsign": str(unit["callsign"]),
        }

        # Track fields
        track_attr = {
            "course": str(unit["course"]),
            "speed": str(unit["speed"])
        }

        # ... existing code ...

        cot = ET.Element('event', attrib=event_attr)
        ET.SubElement(cot, 'point', attrib=point_attr)
        det = ET.SubElement(cot, 'detail')
        ET.SubElement(det, 'remarks').text = str(unit["remarks"])
        ET.SubElement(det, 'contact', attrib=detail_attr)
        ET.SubElement(det, 'track', attrib=track_attr)
```

I don't know if this is the right method, but it works :)

I've updated my fork at https://github.com/aerial-defence/push-cursor-on-target

Thank you again for your help.

Steven

**Pull request merged**
